import { AppShell } from "@/components/app-shell";
import { StatusBanner } from "@/components/status-banner";
import { PageFrame } from "@/components/page-frame";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { ActionChip } from "@/components/action-chip";
import { PreviewCard } from "@/components/preview-card";

/**
 * /emails/[id] (design preview).
 *
 * Email detail skeleton. Static design preview only — does NOT load the email
 * (future source: GET /api/emails/{email_id}), does NOT implement mark-read /
 * mark-unread, and does NOT imply Gmail sync success. The route param is shown
 * only to confirm routing works.
 */
export default async function EmailDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;

  return (
    <AppShell>
      <StatusBanner />
      <div style={{ height: 20 }} />
      <PageFrame
        title="Email detail"
        description="Single email view with AI summary and suggested actions."
      >
        {/* Title region */}
        <section className="mm-card">
          <div className="mm-spread" style={{ marginBottom: 12 }}>
            <div style={{ flex: 1 }}>
              <Skeleton lines={2} widths={["70%", "44%"]} />
            </div>
            <Badge tone="neutral" dot>
              Unread
            </Badge>
          </div>
          <div className="mm-row">
            <ActionChip>Mark read</ActionChip>
            <ActionChip>Mark unread</ActionChip>
            <ActionChip>Open in Gmail</ActionChip>
          </div>
          <p className="mm-muted" style={{ fontSize: 12, marginTop: 12 }}>
            Actions are non-functional in this design preview. Route param
            email_id: <span className="mm-mono">{id}</span>
          </p>
        </section>

        {/* AI summary + suggested action */}
        <div className="mm-grid mm-grid-2">
          <PreviewCard
            title="AI summary"
            badgeLabel="Not connected"
            note="Generated by the AI pipeline (placeholder). Nothing is generated here."
            skeletonLines={4}
          />
          <PreviewCard
            title="Suggested action"
            badgeLabel="AI"
            badgeTone="info"
            note="Suggested actions are static placeholders, not real AI output."
          >
            <div className="mm-row">
              <ActionChip>Reply today</ActionChip>
              <ActionChip>Review</ActionChip>
              <ActionChip>Ignore</ActionChip>
            </div>
          </PreviewCard>
        </div>

        {/* Original content */}
        <PreviewCard
          title="Original email"
          badgeLabel="Not connected"
          note="Original message body (placeholder). No email content is loaded."
          skeletonLines={6}
        />
      </PageFrame>
    </AppShell>
  );
}
